### ISSUE TITLE
SCSS include for font-awesome missing

### ISSUE THREAD

**Issue by sr-rolando** [jekyll-octopod/jekyll-bootflat#4]
It looks like some SCSS include is missing.
In ``assets/css/main.scss``, we see the following:
```scss
@import "bootstrap",
        "bootflat",
        "syntax-highlighting",
        "font-awesome",
        "overrides";
```
However, the ``_sass/`` directory does include a ``_font-awesome.scss`` file.
(As a side effect, this might just be the reason, why a local ``_sass/_overrides.scss`` file is being ignored by ``jekyll b`` or ``jekyll s``.)

Or am I just missing some magic here?

**Comment by haslinger** [comment]
Just a little bit, but not too magic :-) . We have switched to the font-awesome-sass gem, which is included in the [gemspec](https://github.com/jekyll-octopod/jekyll-bootflat/blob/master/jekyll-bootflat.gemspec).
I double checked, if _overrides.scss is ignored. I typically throw in a 
``` .episode_date { font-size: 200%; } ``` for that and it blows up the date nicely.

**Comment by sr-rolando** [comment]
Thanks. The error was indeed some local typo.
